-- MySQL Script generated by MySQL Workbench
-- 02/24/16 09:30:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shortener
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema shortener
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shortener` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `shortener` ;

-- -----------------------------------------------------
-- Table `shortener`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortener`.`user` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `login` VARCHAR(20) NOT NULL COMMENT '',
  `password` VARCHAR(40) NOT NULL COMMENT '',
  `email` VARCHAR(60) NOT NULL COMMENT '',
  UNIQUE INDEX `login_UNIQUE` (`login` ASC)  COMMENT '',
  PRIMARY KEY (`user_id`)  COMMENT '',
  UNIQUE INDEX `user_id_UNIQUE` (`user_id` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortener`.`tag`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortener`.`tag` (
  `tag_id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `title` VARCHAR(40) NOT NULL COMMENT '',
  PRIMARY KEY (`tag_id`)  COMMENT '',
  UNIQUE INDEX `tag_id_UNIQUE` (`tag_id` ASC)  COMMENT '',
  UNIQUE INDEX `title_UNIQUE` (`title` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortener`.`link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortener`.`link` (
  `short_url` VARCHAR(10) NOT NULL COMMENT '',
  `source_url` VARCHAR(1000) NOT NULL COMMENT '',
  `description` VARCHAR(10000) NULL COMMENT '',
  `click_count` BIGINT NULL COMMENT '',
  PRIMARY KEY (`short_url`)  COMMENT '',
  UNIQUE INDEX `short_url_UNIQUE` (`short_url` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shortener`.`tag_link`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shortener`.`tag_link` (
  `tag_id` MEDIUMTEXT NOT NULL COMMENT '',
  `short_url` VARCHAR(10) NOT NULL COMMENT '',
  INDEX `fk_tag_link_tag_idx` (`tag_id` ASC)  COMMENT '',
  INDEX `fk_tag_link_link1_idx` (`short_url` ASC)  COMMENT '',
  PRIMARY KEY (`tag_id`, `short_url`)  COMMENT '',
  CONSTRAINT `fk_tag_link_tag`
    FOREIGN KEY (`tag_id`)
    REFERENCES `shortener`.`tag` (`tag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tag_link_link1`
    FOREIGN KEY (`short_url`)
    REFERENCES `shortener`.`link` (`short_url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
